function MatchList=getMatches(FeatureMatrix,Keypoint_Indices,Full_Locations,StandardDeviations,iteration,AffineTransformsList,Orientations,start,params)
phase=FeatureMatrix(:,end);
MatchList=Matching_Lexicographic(FeatureMatrix(:,1:end-1),phase,Keypoint_Indices,Full_Locations,StandardDeviations,...
                                                            params.alpha,params.beta,params.T_distance,params.T_search,params.init_matchlist_size,...
                                                            AffineTransformsList,Orientations,3,3,iteration~=1,start);